language: php

php:
  - "7.1"
  - "7.2"

branches:
  only:
    - master
    - /^\d+\.\d+$/

before_script:
  - composer install --dev

script:
 - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
 - bash <(curl -s https://codecov.io/bash)
